---
   - name: updating the repository
     apt: upgrade=dist update_cache=yes

   - name: install nginx in ubuntu
     apt:
       name: nginx
       state: latest

   - name: Start nginx     
     service:
       name: nginx
       state: started

