---
- hosts: centos
  #connection: ssh
  #gather_facts: yes
  sudo: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_181"
    java_archive: "{{download_folder}}/jdk-8u181-linux-x64.tar.gz"
  tasks:
  - name: Download Java
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

  - name: Unpack archive
    command: "tar -xvzf {{java_archive}} -C {{download_folder}} creates={{java_name}}"
  - name: Fix ownership
    file: state=directory path={{java_name}} owner=ec2-user group=ec2-user recurse=yes

  - name: Make Java available for system
    alternatives:
       name: java
       path: "{{java_name}}/bin/java"
  - name: Clean up
    file: state=absent path={{java_archive}}
