---
- hosts: "{{ hostname }}"
  gather_facts: false
  tasks:
  - name: git init --bare {{ project }} with the command module
    command: git init --bare {{project}}
    agrs:
      chdir: "{{ git_base_dir }}"
    become_user: git
  - name: Set permissions on {{ git_base_dir}}/{{project}}
    become: yes
    file:
      path: "{{ git_base_dir }}/{{ project }}"
      state: directory
      mode: 0755
      owner: git
      group: git 
      recurse: True
      
